/** أسماء الحقول بالعربية لعرضها في سجل النشاط. */
const LABELS: Record<string, string> = {
  fullName: 'الاسم',
  name: 'الاسم',
  studentNumber: 'رقم الطالب',
  schoolNumber: 'الرقم المدرسي',
  status: 'الحالة',
  statusReason: 'سبب الحالة',
  gender: 'الجنس',
  birthDate: 'تاريخ الميلاد',
  nationalId: 'الرقم الوطني',
  joinDate: 'تاريخ الالتحاق',
  address: 'العنوان',
  notes: 'ملاحظات',
  guardianId: 'ولي الأمر',
  gradeId: 'الصف',
  sectionId: 'الشعبة',
  academicYearId: 'السنة الدراسية',
  phone: 'الهاتف',
  phone2: 'هاتف إضافي',
  amount: 'المبلغ',
  grossAmount: 'المبلغ قبل الخصم',
  discountAmount: 'الخصم',
  netAmount: 'الصافي',
  paidAmount: 'المدفوع',
  date: 'التاريخ',
  dueDate: 'تاريخ الاستحقاق',
  description: 'البيان',
  reason: 'السبب',
  baseSalary: 'الراتب الأساسي',
  salaryType: 'نوع الراتب',
  overtimeRate: 'سعر الساعة الإضافية',
  jobTitle: 'الوظيفة',
  department: 'القسم',
  isActive: 'فعال',
  roleId: 'الدور',
  extraPermissions: 'صلاحيات إضافية',
  revokedPermissions: 'صلاحيات محجوبة',
  permissions: 'الصلاحيات',
  username: 'اسم المستخدم',
  email: 'البريد',
  ownershipPercent: 'نسبة الملكية',
  startDate: 'تاريخ البداية',
  endDate: 'تاريخ النهاية',
  agreedAmount: 'قيمة الاتفاق',
  payeeName: 'المستفيد',
  payerName: 'الدافع',
  paymentMethod: 'طريقة الدفع',
  cashAccountId: 'الصندوق/البنك',
  expenseAccountId: 'نوع المصروف',
  cancelReason: 'سبب الإلغاء',
  number: 'الرقم',
}

export function fieldLabel(field: string): string {
  return LABELS[field] ?? field
}
